apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: metrics-server
spec:
  interval: 1h
  chart:
    spec:
      chart: metrics-server
      version: "3.12.2"
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system
      interval: 1h
  values:
    # Resource limits for Kind cluster
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        memory: 256Mi

    # Required for Kind cluster (kubelet certificates)
    args:
      - --kubelet-insecure-tls
      - --kubelet-preferred-address-types=InternalIP

    # Enable service monitor for Prometheus
    serviceMonitor:
      enabled: true

    # API service configuration
    apiService:
      create: true

    replicas: 1
