apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: alloy
  namespace: monitoring
spec:
  interval: 1h
  timeout: 10m
  chart:
    spec:
      chart: alloy
      version: "0.7.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 1h
  values:
    nameOverride: alloy
    fullnameOverride: alloy
    
    controller:
      type: daemonset
      
    alloy:
      configMap:
        create: true
        content: |
          // Log collection
          local.file_match "logs" {
            path_targets = [
              {__path__ = "/var/log/pods/*/*/*.log"},
            ]
            sync_period = "10s"
          }
          
          loki.source.file "logs" {
            targets    = local.file_match.logs.targets
            forward_to = [loki.write.default.receiver]
            tail_from_end = true
          }
          
          loki.write "default" {
            endpoint {
              name = "loki"
              url = "http://loki-write.monitoring.svc.cluster.local:3100/loki/api/v1/push"
            }
          }
          
          // Metrics collection
          prometheus.scrape "metrics" {
            targets = [
              {"__address__" = "localhost:12345"},
            ]
            forward_to = [prometheus.remote_write.default.receiver]
            job_name = "alloy"
          }
          
          discovery.kubernetes "services" {
            role = "service"
          }

          prometheus.scrape "kubernetes_services" {
            job_name = "kubernetes-services"
            targets = discovery.kubernetes.services.targets
            forward_to = [prometheus.remote_write.default.receiver]
          }

          discovery.kubernetes "pods" {
            role = "pod"
          }

          discovery.relabel "pod_metrics" {
            targets = discovery.kubernetes.pods.targets

            // Keep only pods with prometheus.io/scrape annotation set to true
            rule {
              source_labels = ["__meta_kubernetes_pod_annotation_prometheus_io_scrape"]
              action = "keep"
              regex = "true"
            }

            // Use pod annotations for scrape path
            rule {
              source_labels = ["__meta_kubernetes_pod_annotation_prometheus_io_path"]
              action = "replace"
              target_label = "__metrics_path__"
              regex = "(.+)"
            }

            // Use pod annotations for scrape port
            rule {
              source_labels = ["__address__", "__meta_kubernetes_pod_annotation_prometheus_io_port"]
              action = "replace"
              target_label = "__address__"
              regex = "([^:]+)(?::\\d+)?;(\\d+)"
              replacement = "$1:$2"
            }

            // Add pod labels as metric labels
            rule {
              action = "labelmap"
              regex = "__meta_kubernetes_pod_label_(.+)"
            }

            // Add namespace as a label
            rule {
              source_labels = ["__meta_kubernetes_namespace"]
              action = "replace"
              target_label = "namespace"
            }

            // Add pod name as a label
            rule {
              source_labels = ["__meta_kubernetes_pod_name"]
              action = "replace"
              target_label = "pod"
            }
          }

          prometheus.scrape "kubernetes_pods" {
            job_name = "kubernetes-pods"
            targets = discovery.relabel.pod_metrics.output
            forward_to = [prometheus.remote_write.default.receiver]
          }

          discovery.kubernetes "nodes" {
            role = "node"
          }

          prometheus.scrape "kubernetes_nodes" {
            job_name = "kubernetes-nodes"
            targets = discovery.kubernetes.nodes.targets
            forward_to = [prometheus.remote_write.default.receiver]
          }
          
          prometheus.scrape "kube_state_metrics" {
            job_name = "kube-state-metrics"
            targets = [
              {"__address__" = "kube-prometheus-kube-state-metrics.monitoring.svc.cluster.local:8080"},
            ]
            forward_to = [prometheus.remote_write.default.receiver]
          }
          
          prometheus.remote_write "default" {
            endpoint {
              name = "mimir"
              url = "http://mimir-nginx.monitoring.svc.cluster.local:80/api/v1/push"
            }
          }
          
          // Trace collection
          otelcol.receiver.otlp "traces" {
            grpc {
              endpoint = "0.0.0.0:4317"
            }
            http {
              endpoint = "0.0.0.0:4318"
            }
            output {
              traces = [otelcol.exporter.otlp.tempo.input]
            }
          }
          
          otelcol.exporter.otlp "tempo" {
            client {
              endpoint = "tempo-distributor.monitoring.svc.cluster.local:4317"
              tls {
                insecure = true
              }
            }
          }
      
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
      
      ports:
        - name: http
          port: 12345
          targetPort: 12345
          protocol: TCP
        - name: otlp-grpc
          port: 4317
          targetPort: 4317
          protocol: TCP
        - name: otlp-http
          port: 4318
          targetPort: 4318
          protocol: TCP
    
    service:
      enabled: true
      type: ClusterIP
      ports:
        - name: http
          port: 12345
          targetPort: 12345
          protocol: TCP
        - name: otlp-grpc
          port: 4317
          targetPort: 4317
          protocol: TCP
        - name: otlp-http
          port: 4318
          targetPort: 4318
          protocol: TCP
    
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
    
    rbac:
      create: true

    serviceAccount:
      create: true

    # Mount host paths for log collection
    alloy:
      mounts:
        varlog: true

    controller:
      volumes:
        extra:
          - name: varlog
            hostPath:
              path: /var/log
      volumeMounts:
        extra:
          - name: varlog
            mountPath: /var/log
            readOnly: true
