apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 1h
  timeout: 10m
  chart:
    spec:
      chart: grafana
      version: "8.5.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 1h
  values:
    replicas: 1

    resources:
      requests:
        cpu: 100m
        memory: 256Mi

    sidecar:
      dashboards:
        enabled: true
        label: grafana_dashboard
        labelValue: "1"
        folder: /var/lib/grafana/dashboards
        defaultFolderName: default
        searchNamespace: monitoring
    
    persistence:
      enabled: false
    
    adminUser: admin
    adminPassword: admin

    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          # Mimir datasource
          - name: Mimir
            type: prometheus
            uid: mimir
            url: http://mimir-nginx.monitoring.svc.cluster.local:80/prometheus
            access: proxy
            isDefault: true
            jsonData:
              timeInterval: 60s
              httpMethod: POST
          
          # Loki datasource
          - name: Loki
            type: loki
            uid: loki
            url: http://loki-read.monitoring.svc.cluster.local:3100
            access: proxy
            jsonData:
              maxLines: 1000
              derivedFields:
                - name: TraceID
                  matcherRegex: '"trace_id":"(\w+)"'
                  url: '$${__value.raw}'
                  datasourceUid: tempo
          
          # Tempo datasource
          - name: Tempo
            type: tempo
            uid: tempo
            url: http://tempo-gateway.monitoring.svc.cluster.local:80
            access: proxy
            jsonData:
              tracesToLogs:
                datasourceUid: loki
                spanStartTimeShift: 1h
                spanEndTimeShift: 1h
                tags: ['pod', 'namespace']
                filterByTraceID: true
                filterBySpanID: true
              tracesToMetrics:
                datasourceUid: mimir
                spanStartTimeShift: 1h
                spanEndTimeShift: 1h
                tags: [{ key: 'service.name', value: 'service' }]
              serviceMap:
                datasourceUid: mimir
              nodeGraph:
                enabled: true
              search:
                hide: false
              lokiSearch:
                datasourceUid: loki
          
          # Alertmanager datasource
          - name: Alertmanager
            type: alertmanager
            uid: alertmanager
            url: http://alertmanager-operated.monitoring.svc.cluster.local:9093
            access: proxy
            jsonData:
              implementation: prometheus
    
    dashboards: {}
    
    service:
      type: ClusterIP
      port: 3000
    
    ingress:
      enabled: false
