apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: observability
spec:
  interval: 1h
  timeout: 10m
  chart:
    spec:
      chart: loki
      version: "6.12.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 1h
  values:
    deploymentMode: SimpleScalable

    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: s3
        s3:
          endpoint: loki-minio.observability.svc.cluster.local:9000
          secretAccessKey: supersecret
          accessKeyId: loki
          s3ForcePathStyle: true
          insecure: true
        bucketNames:
          chunks: loki-chunks
          ruler: loki-ruler
          admin: loki-admin
      schemaConfig:
        configs:
          - from: "2024-01-01"
            store: tsdb
            object_store: s3
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
    
    backend:
      replicas: 1
      persistence:
        size: 5Gi
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
    
    read:
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
    
    write:
      replicas: 2
      persistence:
        size: 5Gi
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
    
    minio:
      enabled: true
      replicas: 1
      persistence:
        size: 5Gi
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
      buckets:
        - name: loki-chunks
          policy: none
          purge: false
        - name: loki-ruler
          policy: none
          purge: false
        - name: loki-admin
          policy: none
          purge: false
      rootUser: loki
      rootPassword: supersecret
    
    # Reduce memcached resource requests for Kind cluster
    chunksCache:
      enabled: true
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          memory: 512Mi
      allocatedMemory: 256

    resultsCache:
      enabled: true
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          memory: 256Mi
      allocatedMemory: 128

    gateway:
      enabled: false

    # Disable monitoring by default for Kind cluster
    monitoring:
      selfMonitoring:
        enabled: false
        grafanaAgent:
          installOperator: false
      lokiCanary:
        enabled: false

    # Enable test pod
    test:
      enabled: false
