apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: observability
spec:
  interval: 1h
  chart:
    spec:
      chart: loki
      version: "6.12.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 1h
  values:
    deploymentMode: SimpleScalable
    
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: filesystem
        filesystem:
          chunks_directory: /var/loki/chunks
          rules_directory: /var/loki/rules
      schemaConfig:
        configs:
          - from: "2024-01-01"
            store: tsdb
            object_store: filesystem
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
    
    backend:
      replicas: 1
      persistence:
        size: 5Gi
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
    
    read:
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
    
    write:
      replicas: 2
      persistence:
        size: 5Gi
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
    
    minio:
      enabled: false
    
    gateway:
      enabled: false
    
    # Disable monitoring by default for Kind cluster
    monitoring:
      selfMonitoring:
        enabled: false
        grafanaAgent:
          installOperator: false
      lokiCanary:
        enabled: false
    
    # Enable test pod
    test:
      enabled: false
