apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mimir
  namespace: observability
spec:
  interval: 1h
  chart:
    spec:
      chart: mimir-distributed
      version: "5.5.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 1h
  values:
    mimir:
      structuredConfig:
        common:
          storage:
            backend: filesystem
        blocks_storage:
          backend: filesystem
        alertmanager_storage:
          backend: filesystem
        ruler_storage:
          backend: filesystem
    
    # Reduce resource usage for Kind cluster
    ingester:
      replicas: 2
      persistentVolume:
        enabled: true
        size: 5Gi
      resources:
        requests:
          cpu: 100m
          memory: 512Mi
    
    distributor:
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
    
    querier:
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
    
    query_frontend:
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
    
    store_gateway:
      replicas: 1
      persistentVolume:
        enabled: true
        size: 5Gi
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
    
    compactor:
      replicas: 1
      persistentVolume:
        enabled: true
        size: 5Gi
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
    
    ruler:
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
    
    alertmanager:
      replicas: 1
      persistentVolume:
        enabled: true
        size: 1Gi
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
    
    overrides_exporter:
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
    
    minio:
      enabled: false
